CREATE TABLE white_lightning_spirits (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    spirit_name TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT NOT NULL,
    age TEXT NOT NULL,
    abv TEXT NOT NULL,
    distillery_id INTEGER REFERENCES white_lightning_distilleries(id) ON DELETE CASCADE NOT NULL
);